name: Upload to IPFS

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs: {}

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Install IPFS
        run: |
          sudo snap install ipfs
          ipfs init
          ipfs cat /ipfs/QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc/readme
      - name: Replicate git repository and unpack objects
        run: |
          git clone file://$PWD/.git/ --bare ytdl-patched
          cd ytdl-patched
          git update-server-info
          mv objects/pack/pack-* .
          find . -name 'pack-*.pack' -type f -exec bash -c 'git unpack-objects < {}' \;
          rm -rf pack-* objects/pack/
          git count-objects -v
      - name: Upload to IPFS
        id: upload-ipfs
        run: |
          ipfs add -r -Q ytdl-patched/ | tee upload.log
          IPFS_HASH="$(tail -n1 upload.log)"
          echo $IPFS_HASH
          echo "::set-output name=ipfs-hash::${IPFS_HASH}"
      - name: git clone trial 1
        continue-on-error: true
        run: |
          git clone https://gateway.ipfs.io/ipfs/${{ steps.upload-ipfs.outputs.ipfs-hash }}/ytdl-patched test1
          git -C test1 log -n5
      - name: git clone trial 2
        continue-on-error: true
        run: |
          git clone https://cloudflare-ipfs.com/ipfs/${{ steps.upload-ipfs.outputs.ipfs-hash }}/ytdl-patched test2
          git -C test2 log -n5
      - name: git clone trial 3
        continue-on-error: true
        run: |
          git clone https://ipfs.io/ipfs/${{ steps.upload-ipfs.outputs.ipfs-hash }}/ytdl-patched test3
          git -C test3 log -n5
